import Head from 'next/head';
import styles from '../styles/Home.module.css'
import { Authenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';
import { Amplify, Auth, API } from 'aws-amplify';


Amplify.configure({
  aws_project_region: 'us-east-2',
  aws_cognito_region: 'us-east-2',
  aws_user_pools_id: 'us-east-2_RDVcouh8Y',
  aws_user_pools_web_client_id: '1hqqdp4ia211pdide83afumv27',
  aws_mandatory_sign_in: 'enable',
  aws_cloud_logic_custom: [
    {
      name: 'tiennd124-testAPI',
      endpoint:
        'https://qj29wrd0y1.execute-api.us-east-2.amazonaws.com/v1',
      region: 'us-east-2',
    },
  ],
});

export default function Home() {
  const getUserData = async () => {
    try {
      const user = await Auth.currentAuthenticatedUser();
      const idToken = user.signInUserSession.idToken.jwtToken; 
      console.log("idToken: ", idToken);
      const requestHeader = {
        headers: {
          Authorization: idToken,
        },
        body: {
          email: user.attributes.email,
          name: user.attributes.name,
          age: 18,
        },
      };
      const data = await API.post('tiennd124-testAPI', '/user', requestHeader);
      console.log("Data: ", data);
    } catch (error) {
      console.error('Error fetching user data:', error);
    }
  };
  
  return (
    <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <h1>Tien Nguyen AWS</h1>
    <Authenticator loginMechanisms={['email']} 
                  signUpAttributes={['name']} 
                  socialProviders={['google']}>
        {({ signOut, user }) => (
          <main>
            <h1>
              Hello {user.attributes.name} - {user.attributes.email}
            </h1>
            <p>Secret message</p>
            <button onClick={getUserData}>Call API</button>
            <br/>
            <button onClick={signOut}>Sign out</button>
          </main>
        )}
      </Authenticator>
    </div>
  );
}